In [ ]:
import numpy as np
original_array = np.array([[0, 1], [2, 3]])
print("Original flattened array:", original_array)
max_value = np.max(original_array)
print("Maximum value of the above flattened array:", max_value)
min_value = np.min(original_array)
print("Minimum value of the above flattened array:", min_value)

Original flattened array: [[0 1]
 [2 3]]
Maximum value of the above flattened array: 3
Minimum value of the above flattened array: 0


In [ ]:
import numpy as np
matrix = np.arange(2, 11).reshape(3, 3)
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [5]:
import numpy as np
arr = np.arange(0, 9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
import numpy as np
M1 = np.array([[5, 5],
               [1, 2]])
M2 = np.array([[0, 1],
               [1, 0]])
result = np.dot(M1, M2)
transpose_result = result.T
print("Matrix M1:\n", M1)
print("\nMatrix M2:\n", M2)
print("\nResult of M1 x M2:\n", result)
print("\nTranspose of the resultant matrix:\n", transpose_result)

Matrix M1:
 [[5 5]
 [1 2]]

Matrix M2:
 [[0 1]
 [1 0]]

Result of M1 x M2:
 [[5 5]
 [2 1]]

Transpose of the resultant matrix:
 [[5 2]
 [5 1]]


In [3]:
import numpy as np
matrix = np.array([[6, 1, 1, 3],
                   [4, -2, 5, 1],
                   [2, 8, 7, 6],
                   [3, 1, 9, 7]])
inverse_matrix = np.linalg.inv(matrix)
print(inverse_matrix)

[[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]
